#!/bin/bash
#SBATCH --time=5:00:00
#SBATCH --job-name=cellranger
#SBATCH --nodes=1 --ntasks-per-node=8                    # number of cores and nodes
#SBATCH --mem=20GB                  # memory pool for all cores
#SBATCH --output=/home/nnp9/project/podocoryna/development/cellranger_count.out          # STDOUT
#SBATCH --error=/home/nnp9/project/podocoryna/development/cellranger_count.err          # STDERR

TRANSCRIPTOME="/home/nnp9/project/podocoryna/results/cellranger-isoseq/reference"
FASTQS="/home/nnp9/project/podocoryna/resources/rawdata"

cd /home/nnp9/project/podocoryna/results/cellranger-isoseq/counts
cellranger count --id=podocoryna \
                    --transcriptome=$TRANSCRIPTOME \
                    --fastqs=$FASTQS \
                    --force-cells=8000 \
                    --localcores=8 \
                    --localmem=64
