fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    - id: check-added-large-files
      args: ['--maxkb=100000']
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: fix-encoding-pragma
-   repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
    - id: black
# -   repo: https://gitlab.com/pycqa/flake8
#     rev: 3.9.2
#     hooks:
#     - id: flake8
#       args: ['--ignore=E501,H101,W605']
