#!/bin/bash
#SBATCH --time=50:00:00
#SBATCH --job-name=make_ultrametric
#SBATCH --nodes=1 --ntasks-per-node=12                    # number of cores and nodes
#SBATCH --mem=10GB                  # memory pool for all cores
#SBATCH --output=/home/nnp9/scratch60/podocoryna/slurmfiles/03_make_ultrametric.out          # STDOUT
#SBATCH --error=/home/nnp9/scratch60/podocoryna/slurmfiles/03_make_ultrametric.err          # STDERR

GENETREES=/home/nnp9/scratch60/podocoryna/results/orthofinder_oct17_repeat/Results_Oct17/Resolved_Gene_Trees
OUTDIR=/home/nnp9/scratch60/podocoryna/results/orthofinder_oct17_repeat/Results_Oct17/Resolved_Gene_Trees_Ultrametric

#conda activate orthofinder

cd $GENETREES
TREES=$(find ~+ -name '*.txt' -type f)

for i in $TREES
do
	make_ultrametric.py -r 1 $i;
done

mkdir $OUTDIR
mv *.ultrametric.tre $OUTDIR
