#!/bin/bash

##conda activate snakemake
TRANSCRIPTOME=/home/nnp9/project/podocoryna/resources/isoseq/cogent_bysally/Male_Med.Cogent.hq_transcripts.fasta.no5merge.collapsed.filtered.rep.fa
ORIGINAL_GFF=/home/nnp9/project/podocoryna/resources/isoseq/cogent_bysally/Male_Med.Cogent.hq_transcripts.fasta.no5merge.collapsed.filtered.gff
SCRIPTS=/home/nnp9/project/podocoryna/workflow/scripts

python $SCRIPTS/fix_gtf.py $TRANSCRIPTOME $ORIGINAL_GFF

LIST_OF_TRANSCRIPTS=/home/nnp9/scratch60/podocoryna/results/treeinform/threshold_4/Podocoryna_carnea.collapsed.fasta.transcripts.collapsed.list.txt
FIXED_GFF=/home/nnp9/project/podocoryna/resources/isoseq/cogent_bysally/Male_Med.Cogent.hq_transcripts.fasta.no5merge.collapsed.filtered.gff.fixed.gff
OUTDIR=/home/nnp9/scratch60/podocoryna/results/treeinform/threshold_4

python $SCRIPTS/select_from_gtf.py $LIST_OF_TRANSCRIPTS $FIXED_GFF $OUTDIR
