species: Podocoryna_carnea

# Path to accession numbers and links for public data download
targets: config/download_targets.tsv

# Reference before processing:
reference:
  path: resources/isoseq/Male_Med.ALL.Clustered.hq.CLEAN.cd_99.Min200.fasta
  filename: Male_Med.ALL.Clustered.hq.CLEAN.cd_99.Min200.fasta
  filestem: Male_Med.ALL.Clustered.hq.CLEAN.cd_99.Min200
  gtf: resources/isoseq/Male_Med.ALL.Clustered.hq.CLEAN.cd_99.Min200.fasta.eggnog.positive.gtf
  gtfname: Male_Med.ALL.Clustered.hq.CLEAN.cd_99.Min200.fasta.eggnog.positive.gtf

# Sample batches
batch:
  Podo1: STD_v3
  Podo2: HT_v3
  Podo3: HT_v3
  Podo4: HT_v3
  Podo5: HT_v3
