#!/bin/bash
#SBATCH --time=1:00:00
#SBATCH --job-name=cellranger
#SBATCH --nodes=1 --ntasks-per-node=8                    # number of cores and nodes
#SBATCH --mem=20GB                  # memory pool for all cores
#SBATCH --output=/home/nnp9/scratch60/podocoryna/slurmfiles/53_cellranger_reference.out          # STDOUT
#SBATCH --error=/home/nnp9/scratch60/podocoryna/slurmfiles/53_cellranger_reference.err          # STDERR

REFERENCE=/home/nnp9/scratch60/podocoryna/results/treeinform/threshold_5/Podocoryna_carnea.collapsed.fasta.transcripts.collapsed.fasta
GTF=/home/nnp9/scratch60/podocoryna/results/treeinform/threshold_5/Male_Med.Cogent.hq_transcripts.fasta.no5merge.collapsed.filtered.gff.fixed.selected.gtf
OUTDIR=/home/nnp9/scratch60/podocoryna/results/treeinform/threshold_5

cd $OUTDIR
cellranger mkref --genome=reference --fasta=$REFERENCE --genes=$GTF
